### PR TITLE
Added my tic tac toe game

### PR DESCRIPTION
**Pull request by Satendra124**

### CODE REVIEW

**Comment by nishantwrp** [comment]
Please provide a url where you have deployed your game.

**Comment by Satendra124** [comment]
https://satendra124.github.io/Tictactoe/index.html

**Comment by Satendra124** [comment]
the single player mode is still have bugs .

**Comment by nishantwrp** [comment]
@Satendra124 The URL is not working. And maybe you can fix your bugs and then open a new PR.

**Comment by Satendra124** [comment]
@nishantwrp  https://satendra124.github.io/Tictactoe/Index.html 
This should work fine 
and i am trying to remove those bugs Thanks 😄

**Comment by nishantwrp** [comment]
@Satendra124 Ok, then. I'm marking this PR as a draft for now. You can ping me when it's ready for submission. Thanks!

**Comment by Satendra124** [comment]
https://satendra124.github.io/Tictactoe/Index.html 
Updated the code . Now the ai don't have any bugs but still its work under progress since you can defeat the ai due to random moves ai plays when not in danger to loose

**Comment by arron-tij** [comment]
The UI and animations are great but as you said the logic for the bot is not perfect. You can see other merged PR's for its correct implementation and learn about minimax function.

**Comment by Satendra124** [comment]
Ok for sure

**Pull request merged**
